name: Aggregit

on:
  issues:
    types: [labeled, unlabeled]

jobs:
  recordMetrics:
    runs-on: ubuntu-latest
    steps:
    - uses: bdougie/_test_for_mike@master
      with:
        githubToken: ${{ secrets.BDOUGIE_TOKEN }}
